import {
  ALL_SPELL_IDS,
  DEFAULT_ARMOR,
  DEFAULT_EQUIPPED_SPELLS,
  DEFAULT_UNLOCKED_SPELLS,
  DEFAULT_WEAPON,
  FIXED_STEP_MS,
  PLAYER_BASE_STATS,
} from "./config.js";

export function createInitialState() {
  return {
    mode: "title",
    time: {
      now: 0,
      accumulator: 0,
      step: FIXED_STEP_MS,
    },
    camera: {
      x: 0,
      y: 0,
      shake: 0,
    },
    player: null,
    enemies: [],
    projectiles: [],
    pickups: [],
    effects: [],
    arenaRun: {
      encounterIndex: 0,
      arenaIndex: 0,
      waveIndex: 0,
      regionId: "emberwood",
      activeArenaId: null,
      remainingWaves: 0,
      clearedArenas: 0,
      bossSpawned: false,
      isBossArena: false,
      chainingBosses: true,
      pendingSummary: null,
      queuedSpawns: [],
      waveTimerMs: 0,
      encounterRewardGold: 0,
      encounterRewardMaterials: 0,
      rareWave: false,
      runGold: 0,
      runMaterials: 0,
      victory: false,
      seedOffset: 0,
    },
    progression: {
      gold: 0,
      materials: 0,
      unlockedSpells: [...DEFAULT_UNLOCKED_SPELLS],
      spellLevels: Object.fromEntries(ALL_SPELL_IDS.map((id) => [id, 1])),
      purchasedUpgrades: [],
      equippedSpells: [...DEFAULT_EQUIPPED_SPELLS],
      equippedWeapon: DEFAULT_WEAPON,
      equippedArmor: DEFAULT_ARMOR,
    },
    ui: {
      hoveredSpellId: null,
      selectedShopItemId: null,
      notifications: [],
      overlayMessage: "",
      reviewNotes: [],
      selectedHubTab: "summary",
    },
    input: {
      moveX: 0,
      moveY: 0,
      aimWorldX: 0,
      aimWorldY: 0,
      primaryPressed: false,
      spellPressed: [false, false, false],
      dashPressed: false,
      pausePressed: false,
    },
    runtime: {
      statsDirty: true,
      playerBaseStats: { ...PLAYER_BASE_STATS },
      playerDerivedStats: { ...PLAYER_BASE_STATS },
      hoveredButtons: [],
      lastArenaClearAt: 0,
      lastDamageAt: 0,
      nextEntityId: 1,
      overlayBindingsInstalled: false,
      saveAvailable: true,
    },
    rngSeed: 123456789,
  };
}
