export function createEnemy(id, definition, position) {
  return {
    id,
    type: "enemy",
    definitionId: definition.id,
    team: "enemy",
    role: definition.role,
    position: { ...position },
    velocity: { x: 0, y: 0 },
    radius: definition.radius ?? 16,
    maxHp: definition.maxHp,
    hp: definition.maxHp,
    speed: definition.speed,
    contactDamage: definition.contactDamage,
    attackRange: definition.attackRange,
    attackCooldownMs: definition.attackCooldownMs,
    attackTimerMs: definition.attackCooldownMs * 0.35,
    aiType: definition.aiType,
    rewards: { ...definition.rewards },
    elite: Boolean(definition.elite),
    boss: false,
    statusEffects: [],
    summonCount: 0,
    maxSummons: definition.maxSummons ?? 0,
    projectileSpeed: definition.projectileSpeed ?? 240,
    attackDamage: definition.attackDamage ?? definition.contactDamage,
    preferredDistance: definition.preferredDistance ?? definition.attackRange * 0.8,
    damageFlashMs: 0,
    telegraphMs: 0,
    alive: true,
  };
}
